// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_auth_template/test/widgets/enhanced_login_form_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_auth_template/core/network/api_response.dart' as _i4;
import 'package:flutter_auth_template/core/storage/secure_storage_service.dart'
    as _i12;
import 'package:flutter_auth_template/data/models/auth_response.dart' as _i3;
import 'package:flutter_auth_template/domain/entities/auth_state.dart' as _i2;
import 'package:flutter_auth_template/infrastructure/services/auth/biometric_service.dart'
    as _i9;
import 'package:flutter_auth_template/infrastructure/services/auth/oauth_service.dart'
    as _i11;
import 'package:flutter_auth_template/presentation/providers/auth_provider.dart'
    as _i5;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i7;
import 'package:local_auth/local_auth.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:state_notifier/state_notifier.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthState_0 extends _i1.SmartFake implements _i2.AuthState {
  _FakeAuthState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTwoFactorSetupResponse_1 extends _i1.SmartFake
    implements _i3.TwoFactorSetupResponse {
  _FakeTwoFactorSetupResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiResponse_2<T> extends _i1.SmartFake
    implements _i4.ApiResponse<T> {
  _FakeApiResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthNotifier extends _i1.Mock implements _i5.AuthNotifier {
  MockAuthNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get mounted =>
      (super.noSuchMethod(Invocation.getter(#mounted), returnValue: false)
          as bool);

  @override
  _i6.Stream<_i2.AuthState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i2.AuthState>.empty(),
          )
          as _i6.Stream<_i2.AuthState>);

  @override
  _i2.AuthState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAuthState_0(this, Invocation.getter(#state)),
          )
          as _i2.AuthState);

  @override
  _i2.AuthState get debugState =>
      (super.noSuchMethod(
            Invocation.getter(#debugState),
            returnValue: _FakeAuthState_0(this, Invocation.getter(#debugState)),
          )
          as _i2.AuthState);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  set onError(_i7.ErrorListener? _onError) => super.noSuchMethod(
    Invocation.setter(#onError, _onError),
    returnValueForMissingStub: null,
  );

  @override
  set state(_i2.AuthState? value) => super.noSuchMethod(
    Invocation.setter(#state, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> register(String? email, String? password, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#register, [email, password, name]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> forgotPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [email]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> resetPassword(String? token, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [token, password]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> changePassword(
    String? currentPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [currentPassword, newPassword]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> verifyEmail(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> resendEmailVerification(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resendEmailVerification, [email]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.TwoFactorSetupResponse> setup2FA() =>
      (super.noSuchMethod(
            Invocation.method(#setup2FA, []),
            returnValue: _i6.Future<_i3.TwoFactorSetupResponse>.value(
              _FakeTwoFactorSetupResponse_1(
                this,
                Invocation.method(#setup2FA, []),
              ),
            ),
          )
          as _i6.Future<_i3.TwoFactorSetupResponse>);

  @override
  _i6.Future<void> enable2FA(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#enable2FA, [code]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> verify2FA(
    String? code, {
    String? token,
    bool? isBackup = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #verify2FA,
              [code],
              {#token: token, #isBackup: isBackup},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> disable2FA(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#disable2FA, [password]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> oauthLogin(
    String? provider,
    String? code, {
    String? state,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#oauthLogin, [provider, code], {#state: state}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> requestMagicLink(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#requestMagicLink, [email]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> verifyMagicLink(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#verifyMagicLink, [token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateProfile(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [data]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> refreshUser() =>
      (super.noSuchMethod(
            Invocation.method(#refreshUser, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> signOutFromOAuth() =>
      (super.noSuchMethod(
            Invocation.method(#signOutFromOAuth, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  bool updateShouldNotify(_i2.AuthState? old, _i2.AuthState? current) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [old, current]),
            returnValue: false,
          )
          as bool);

  @override
  _i7.RemoveListener addListener(
    _i8.Listener<_i2.AuthState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addListener,
              [listener],
              {#fireImmediately: fireImmediately},
            ),
            returnValue: () {},
          )
          as _i7.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [BiometricService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBiometricService extends _i1.Mock implements _i9.BiometricService {
  MockBiometricService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.ApiResponse<_i9.BiometricAvailability>>
  checkBiometricAvailability() =>
      (super.noSuchMethod(
            Invocation.method(#checkBiometricAvailability, []),
            returnValue:
                _i6.Future<_i4.ApiResponse<_i9.BiometricAvailability>>.value(
                  _FakeApiResponse_2<_i9.BiometricAvailability>(
                    this,
                    Invocation.method(#checkBiometricAvailability, []),
                  ),
                ),
          )
          as _i6.Future<_i4.ApiResponse<_i9.BiometricAvailability>>);

  @override
  _i6.Future<_i4.ApiResponse<bool>> authenticateWithBiometrics({
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#authenticateWithBiometrics, [], {
              #reason: reason,
            }),
            returnValue: _i6.Future<_i4.ApiResponse<bool>>.value(
              _FakeApiResponse_2<bool>(
                this,
                Invocation.method(#authenticateWithBiometrics, [], {
                  #reason: reason,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.ApiResponse<bool>>);

  @override
  _i6.Future<_i4.ApiResponse<String>> enableBiometricAuth() =>
      (super.noSuchMethod(
            Invocation.method(#enableBiometricAuth, []),
            returnValue: _i6.Future<_i4.ApiResponse<String>>.value(
              _FakeApiResponse_2<String>(
                this,
                Invocation.method(#enableBiometricAuth, []),
              ),
            ),
          )
          as _i6.Future<_i4.ApiResponse<String>>);

  @override
  _i6.Future<_i4.ApiResponse<String>> disableBiometricAuth() =>
      (super.noSuchMethod(
            Invocation.method(#disableBiometricAuth, []),
            returnValue: _i6.Future<_i4.ApiResponse<String>>.value(
              _FakeApiResponse_2<String>(
                this,
                Invocation.method(#disableBiometricAuth, []),
              ),
            ),
          )
          as _i6.Future<_i4.ApiResponse<String>>);

  @override
  _i6.Future<bool> isBiometricAuthEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isBiometricAuthEnabled, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i9.BiometricCapability?> getBiometricCapability() =>
      (super.noSuchMethod(
            Invocation.method(#getBiometricCapability, []),
            returnValue: _i6.Future<_i9.BiometricCapability?>.value(),
          )
          as _i6.Future<_i9.BiometricCapability?>);

  @override
  _i6.Future<bool> authenticateForLogin() =>
      (super.noSuchMethod(
            Invocation.method(#authenticateForLogin, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i4.ApiResponse<_i9.BiometricStatus>> getBiometricStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getBiometricStatus, []),
            returnValue: _i6.Future<_i4.ApiResponse<_i9.BiometricStatus>>.value(
              _FakeApiResponse_2<_i9.BiometricStatus>(
                this,
                Invocation.method(#getBiometricStatus, []),
              ),
            ),
          )
          as _i6.Future<_i4.ApiResponse<_i9.BiometricStatus>>);

  @override
  _i6.Future<_i4.ApiResponse<bool>> promptBiometricSetup() =>
      (super.noSuchMethod(
            Invocation.method(#promptBiometricSetup, []),
            returnValue: _i6.Future<_i4.ApiResponse<bool>>.value(
              _FakeApiResponse_2<bool>(
                this,
                Invocation.method(#promptBiometricSetup, []),
              ),
            ),
          )
          as _i6.Future<_i4.ApiResponse<bool>>);

  @override
  List<String> getBiometricTypeNames(List<_i10.BiometricType>? types) =>
      (super.noSuchMethod(
            Invocation.method(#getBiometricTypeNames, [types]),
            returnValue: <String>[],
          )
          as List<String>);
}

/// A class which mocks [OAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOAuthService extends _i1.Mock implements _i11.OAuthService {
  MockOAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.ApiResponse<_i11.GoogleSignInResult>> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue:
                _i6.Future<_i4.ApiResponse<_i11.GoogleSignInResult>>.value(
                  _FakeApiResponse_2<_i11.GoogleSignInResult>(
                    this,
                    Invocation.method(#signInWithGoogle, []),
                  ),
                ),
          )
          as _i6.Future<_i4.ApiResponse<_i11.GoogleSignInResult>>);

  @override
  _i6.Future<void> signOutFromGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signOutFromGoogle, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isGoogleSignedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isGoogleSignedIn, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<String?> getGoogleAuthToken(_i11.GoogleSignInAccount? account) =>
      (super.noSuchMethod(
            Invocation.method(#getGoogleAuthToken, [account]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i12.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> storeAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#storeAccessToken, [token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> removeAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#removeAccessToken, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> storeRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#storeRefreshToken, [token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> removeRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#removeRefreshToken, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteRefreshToken, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> storeUserData(Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
            Invocation.method(#storeUserData, [userData]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>?> getUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, []),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<void> removeUserData() =>
      (super.noSuchMethod(
            Invocation.method(#removeUserData, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setBiometricEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setBiometricEnabled, [enabled]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> getBiometricEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#getBiometricEnabled, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> storeBiometricEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#storeBiometricEnabled, [enabled]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isBiometricEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isBiometricEnabled, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> storeDeviceId(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#storeDeviceId, [deviceId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> getDeviceId() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceId, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> storeFcmToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#storeFcmToken, [token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> getFcmToken() =>
      (super.noSuchMethod(
            Invocation.method(#getFcmToken, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> storeLastLogin(DateTime? timestamp) =>
      (super.noSuchMethod(
            Invocation.method(#storeLastLogin, [timestamp]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<DateTime?> getLastLogin() =>
      (super.noSuchMethod(
            Invocation.method(#getLastLogin, []),
            returnValue: _i6.Future<DateTime?>.value(),
          )
          as _i6.Future<DateTime?>);

  @override
  _i6.Future<void> storeTwoFactorSecret(String? secret) =>
      (super.noSuchMethod(
            Invocation.method(#storeTwoFactorSecret, [secret]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> getTwoFactorSecret() =>
      (super.noSuchMethod(
            Invocation.method(#getTwoFactorSecret, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> removeTwoFactorSecret() =>
      (super.noSuchMethod(
            Invocation.method(#removeTwoFactorSecret, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> store(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#store, [key, value]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> get(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#get, [key]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> write({required String? key, required String? value}) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {#key: key, #value: value}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> read({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {#key: key}),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> delete({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {#key: key}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isKeyRotationNeeded() =>
      (super.noSuchMethod(
            Invocation.method(#isKeyRotationNeeded, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> rotateEncryptionKeys() =>
      (super.noSuchMethod(
            Invocation.method(#rotateEncryptionKeys, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<Map<String, String>> getAllItems() =>
      (super.noSuchMethod(
            Invocation.method(#getAllItems, []),
            returnValue: _i6.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i6.Future<Map<String, String>>);

  @override
  _i6.Future<void> storeJsonData(String? key, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#storeJsonData, [key, data]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>?> getJsonData(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getJsonData, [key]),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<void> saveUserProfile(dynamic profile) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserProfile, [profile]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<dynamic> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);
}
