// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_auth_template/test/providers/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_auth_template/core/network/api_response.dart' as _i2;
import 'package:flutter_auth_template/core/storage/secure_storage_service.dart'
    as _i10;
import 'package:flutter_auth_template/data/models/auth_request.dart' as _i6;
import 'package:flutter_auth_template/data/models/auth_response.dart' as _i7;
import 'package:flutter_auth_template/domain/entities/user.dart' as _i5;
import 'package:flutter_auth_template/services/auth_service.dart' as _i3;
import 'package:flutter_auth_template/services/oauth_service.dart' as _i8;
import 'package:google_sign_in/google_sign_in.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse<_i5.User>> login(_i6.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.User>>.value(
              _FakeApiResponse_0<_i5.User>(
                this,
                Invocation.method(#login, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.User>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.User>> register(
    _i6.RegisterRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.User>>.value(
              _FakeApiResponse_0<_i5.User>(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.User>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.User>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.User>>.value(
              _FakeApiResponse_0<_i5.User>(
                this,
                Invocation.method(#getCurrentUser, []),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.User>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.User>> updateProfile(
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [data]),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.User>>.value(
              _FakeApiResponse_0<_i5.User>(
                this,
                Invocation.method(#updateProfile, [data]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.User>>);

  @override
  _i4.Future<_i2.ApiResponse<String>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<_i2.ApiResponse<String>>.value(
              _FakeApiResponse_0<String>(this, Invocation.method(#logout, [])),
            ),
          )
          as _i4.Future<_i2.ApiResponse<String>>);

  @override
  _i4.Future<_i2.ApiResponse<String>> forgotPassword(
    _i6.ForgotPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue: _i4.Future<_i2.ApiResponse<String>>.value(
              _FakeApiResponse_0<String>(
                this,
                Invocation.method(#forgotPassword, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<String>>);

  @override
  _i4.Future<_i2.ApiResponse<String>> resetPassword(
    _i6.ResetPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i4.Future<_i2.ApiResponse<String>>.value(
              _FakeApiResponse_0<String>(
                this,
                Invocation.method(#resetPassword, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<String>>);

  @override
  _i4.Future<_i2.ApiResponse<String>> changePassword(
    _i6.ChangePasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [request]),
            returnValue: _i4.Future<_i2.ApiResponse<String>>.value(
              _FakeApiResponse_0<String>(
                this,
                Invocation.method(#changePassword, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<String>>);

  @override
  _i4.Future<_i2.ApiResponse<String>> verifyEmail(
    _i6.VerifyEmailRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [request]),
            returnValue: _i4.Future<_i2.ApiResponse<String>>.value(
              _FakeApiResponse_0<String>(
                this,
                Invocation.method(#verifyEmail, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<String>>);

  @override
  _i4.Future<_i2.ApiResponse<String>> resendEmailVerification(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resendEmailVerification, [email]),
            returnValue: _i4.Future<_i2.ApiResponse<String>>.value(
              _FakeApiResponse_0<String>(
                this,
                Invocation.method(#resendEmailVerification, [email]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<String>>);

  @override
  _i4.Future<_i2.ApiResponse<_i7.TwoFactorSetupResponse>> setup2FA() =>
      (super.noSuchMethod(
            Invocation.method(#setup2FA, []),
            returnValue:
                _i4.Future<_i2.ApiResponse<_i7.TwoFactorSetupResponse>>.value(
                  _FakeApiResponse_0<_i7.TwoFactorSetupResponse>(
                    this,
                    Invocation.method(#setup2FA, []),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<_i7.TwoFactorSetupResponse>>);

  @override
  _i4.Future<_i2.ApiResponse<String>> enable2FA(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#enable2FA, [code]),
            returnValue: _i4.Future<_i2.ApiResponse<String>>.value(
              _FakeApiResponse_0<String>(
                this,
                Invocation.method(#enable2FA, [code]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<String>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.User>> verify2FA(
    _i6.VerifyTwoFactorRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verify2FA, [request]),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.User>>.value(
              _FakeApiResponse_0<_i5.User>(
                this,
                Invocation.method(#verify2FA, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.User>>);

  @override
  _i4.Future<_i2.ApiResponse<String>> disable2FA(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#disable2FA, [password]),
            returnValue: _i4.Future<_i2.ApiResponse<String>>.value(
              _FakeApiResponse_0<String>(
                this,
                Invocation.method(#disable2FA, [password]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<String>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.User>> oauthLogin(
    _i6.OAuthLoginRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#oauthLogin, [request]),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.User>>.value(
              _FakeApiResponse_0<_i5.User>(
                this,
                Invocation.method(#oauthLogin, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.User>>);

  @override
  _i4.Future<_i2.ApiResponse<String>> requestMagicLink(
    _i6.MagicLinkRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#requestMagicLink, [request]),
            returnValue: _i4.Future<_i2.ApiResponse<String>>.value(
              _FakeApiResponse_0<String>(
                this,
                Invocation.method(#requestMagicLink, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<String>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.User>> verifyMagicLink(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#verifyMagicLink, [token]),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.User>>.value(
              _FakeApiResponse_0<_i5.User>(
                this,
                Invocation.method(#verifyMagicLink, [token]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.User>>);

  @override
  _i4.Future<bool> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [OAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOAuthService extends _i1.Mock implements _i8.OAuthService {
  MockOAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse<_i8.GoogleSignInResult>> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue:
                _i4.Future<_i2.ApiResponse<_i8.GoogleSignInResult>>.value(
                  _FakeApiResponse_0<_i8.GoogleSignInResult>(
                    this,
                    Invocation.method(#signInWithGoogle, []),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<_i8.GoogleSignInResult>>);

  @override
  _i4.Future<void> signOutFromGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signOutFromGoogle, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isGoogleSignedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isGoogleSignedIn, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i9.GoogleSignInAccount?> getCurrentGoogleUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentGoogleUser, []),
            returnValue: _i4.Future<_i9.GoogleSignInAccount?>.value(),
          )
          as _i4.Future<_i9.GoogleSignInAccount?>);

  @override
  _i4.Future<_i2.ApiResponse<_i8.AppleSignInResult>> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue:
                _i4.Future<_i2.ApiResponse<_i8.AppleSignInResult>>.value(
                  _FakeApiResponse_0<_i8.AppleSignInResult>(
                    this,
                    Invocation.method(#signInWithApple, []),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<_i8.AppleSignInResult>>);

  @override
  _i4.Future<_i2.ApiResponse<_i8.FacebookSignInResult>> signInWithFacebook() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithFacebook, []),
            returnValue:
                _i4.Future<_i2.ApiResponse<_i8.FacebookSignInResult>>.value(
                  _FakeApiResponse_0<_i8.FacebookSignInResult>(
                    this,
                    Invocation.method(#signInWithFacebook, []),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<_i8.FacebookSignInResult>>);

  @override
  _i4.Future<_i2.ApiResponse<_i8.GitHubSignInResult>> signInWithGitHub() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGitHub, []),
            returnValue:
                _i4.Future<_i2.ApiResponse<_i8.GitHubSignInResult>>.value(
                  _FakeApiResponse_0<_i8.GitHubSignInResult>(
                    this,
                    Invocation.method(#signInWithGitHub, []),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<_i8.GitHubSignInResult>>);

  @override
  _i4.Future<_i2.ApiResponse<_i8.DiscordSignInResult>> signInWithDiscord() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithDiscord, []),
            returnValue:
                _i4.Future<_i2.ApiResponse<_i8.DiscordSignInResult>>.value(
                  _FakeApiResponse_0<_i8.DiscordSignInResult>(
                    this,
                    Invocation.method(#signInWithDiscord, []),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<_i8.DiscordSignInResult>>);
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i10.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> storeAccessToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#storeAccessToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> removeAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#removeAccessToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> storeRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#storeRefreshToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> removeRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#removeRefreshToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> storeUserData(Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
            Invocation.method(#storeUserData, [userData]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, []),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> removeUserData() =>
      (super.noSuchMethod(
            Invocation.method(#removeUserData, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setBiometricEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setBiometricEnabled, [enabled]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> getBiometricEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#getBiometricEnabled, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> storeDeviceId(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#storeDeviceId, [deviceId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getDeviceId() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceId, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> storeFcmToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#storeFcmToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getFcmToken() =>
      (super.noSuchMethod(
            Invocation.method(#getFcmToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> storeLastLogin(DateTime? timestamp) =>
      (super.noSuchMethod(
            Invocation.method(#storeLastLogin, [timestamp]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<DateTime?> getLastLogin() =>
      (super.noSuchMethod(
            Invocation.method(#getLastLogin, []),
            returnValue: _i4.Future<DateTime?>.value(),
          )
          as _i4.Future<DateTime?>);

  @override
  _i4.Future<void> storeTwoFactorSecret(String? secret) =>
      (super.noSuchMethod(
            Invocation.method(#storeTwoFactorSecret, [secret]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getTwoFactorSecret() =>
      (super.noSuchMethod(
            Invocation.method(#getTwoFactorSecret, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> removeTwoFactorSecret() =>
      (super.noSuchMethod(
            Invocation.method(#removeTwoFactorSecret, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> store(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#store, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> get(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#get, [key]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> write({required String? key, required String? value}) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {#key: key, #value: value}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> read({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {#key: key}),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> delete({required String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {#key: key}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, String>> getAllItems() =>
      (super.noSuchMethod(
            Invocation.method(#getAllItems, []),
            returnValue: _i4.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i4.Future<Map<String, String>>);

  @override
  _i4.Future<void> storeJsonData(String? key, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#storeJsonData, [key, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getJsonData(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getJsonData, [key]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> saveUserProfile(dynamic profile) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserProfile, [profile]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<dynamic> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);
}
