global:
  resolve_timeout: 5m
  smtp_from: 'monitoring@enterprise-auth.com'
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_auth_username: '${SMTP_USER}'
  smtp_auth_password: '${SMTP_PASSWORD}'
  # slack_api_url: '${SLACK_WEBHOOK_URL}'  # Disabled for initial testing

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route tree for alert routing
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 1h
    
    # Security alerts - immediate notification to security team
    - match:
        component: security
      receiver: 'security-alerts'
      group_wait: 0s
      repeat_interval: 30m
    
    # Database alerts
    - match:
        component: database
      receiver: 'database-alerts'
      group_wait: 30s
      repeat_interval: 4h
    
    # Business metrics
    - match:
        component: business
      receiver: 'business-alerts'
      group_wait: 5m
      repeat_interval: 24h

# Receivers configuration
receivers:
  - name: 'default'
    email_configs:
      - to: 'ops-team@enterprise-auth.com'
        send_resolved: true
        headers:
          Subject: '[{{ .GroupLabels.severity | toUpper }}] {{ .GroupLabels.alertname }} - Enterprise Auth'
        html: |
          <h2>🚨 Alert: {{ .GroupLabels.alertname }}</h2>
          <p><b>Severity:</b> {{ .GroupLabels.severity }}</p>
          <p><b>Summary:</b> {{ .Annotations.summary }}</p>
          <p><b>Description:</b> {{ .Annotations.description }}</p>
          <p><b>Time:</b> {{ .StartsAt.Format "2006-01-02 15:04:05" }}</p>
          <hr>
          <p><a href="http://localhost:3001">View in Grafana</a></p>

  - name: 'critical-alerts'
    email_configs:
      - to: 'critical-alerts@enterprise-auth.com'
        send_resolved: true
    # slack_configs:  # Disabled for initial testing
    #   - channel: '#critical-alerts'
    #     title: '🔴 CRITICAL: {{ .GroupLabels.alertname }}'
    #     text: '{{ .Annotations.summary }}\n{{ .Annotations.description }}'
    #     send_resolved: true
    # pagerduty_configs:  # Disabled for initial testing
    #   - service_key: '${PAGERDUTY_SERVICE_KEY}'
    #     description: '{{ .GroupLabels.alertname }}: {{ .Annotations.summary }}'

  - name: 'security-alerts'
    email_configs:
      - to: 'security@enterprise-auth.com'
        send_resolved: true
    # slack_configs:  # Disabled for initial testing
    #   - channel: '#security-alerts'
    #     title: '🔐 Security Alert: {{ .GroupLabels.alertname }}'
    #     text: '{{ .Annotations.summary }}\n{{ .Annotations.description }}'
    #     send_resolved: true

  - name: 'database-alerts'
    email_configs:
      - to: 'database-team@enterprise-auth.com'
        send_resolved: true
    # slack_configs:  # Disabled for initial testing
    #   - channel: '#database-alerts'
    #     title: '🗄️ Database Alert: {{ .GroupLabels.alertname }}'
    #     text: '{{ .Annotations.summary }}\n{{ .Annotations.description }}'

  - name: 'business-alerts'
    email_configs:
      - to: 'business-metrics@enterprise-auth.com'
        send_resolved: false
    # slack_configs:  # Disabled for initial testing  
    #   - channel: '#business-metrics'
    #     title: '📊 Business Metric: {{ .GroupLabels.alertname }}'
    #     text: '{{ .Annotations.summary }}\n{{ .Annotations.description }}'
    #     send_resolved: false

# Inhibition rules
inhibit_rules:
  # Inhibit warning alerts if critical alert is firing for same component
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'component']
  
  # Inhibit info alerts if warning or critical is firing
  - source_match_re:
      severity: 'warning|critical'
    target_match:
      severity: 'info'
    equal: ['alertname', 'component']