# Prometheus Configuration for Enterprise Auth Template - Production Setup
# This configuration targets containerized services

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'enterprise-auth'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

# Load rules once and periodically evaluate them
rule_files:
  - '/etc/prometheus/rules/*.yml'

# Scrape configurations for containerized services
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Backend API metrics (containerized)
  - job_name: 'backend-api'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['backend:8000']  # Service name from Docker Compose
        labels:
          service: 'backend'
          component: 'api'

  # PostgreSQL exporter
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgresql'
          component: 'database'

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
          component: 'cache'

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node'
          component: 'system'

  # Frontend application (if metrics endpoint is added)
  - job_name: 'frontend'
    metrics_path: '/api/metrics'  # Next.js API route for metrics
    scrape_interval: 30s
    static_configs:
      - targets: ['frontend:3000']
        labels:
          service: 'frontend'
          component: 'ui'
    scrape_timeout: 5s