# Prometheus Configuration for Enterprise Auth Template
# This configuration sets up Prometheus to scrape metrics from the application

global:
  scrape_interval: 15s          # How frequently to scrape targets
  evaluation_interval: 15s      # How frequently to evaluate rules
  external_labels:
    monitor: 'enterprise-auth'
    environment: 'production'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - 'alertmanager:9093'

# Load rules once and periodically evaluate them
rule_files:
  - '/etc/prometheus/rules/*.yml'

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Backend API metrics
  - job_name: 'backend-api'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8001']  # Use host.docker.internal to reach localhost from container
        labels:
          service: 'backend'
          component: 'api'

  # PostgreSQL exporter (commented out until postgres is running)
  # - job_name: 'postgresql'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']
  #       labels:
  #         service: 'postgresql'
  #         component: 'database'

  # Redis exporter (commented out until redis is running)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
  #       labels:
  #         service: 'redis'
  #         component: 'cache'

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node'
          component: 'system'

  # Frontend application (if instrumented)
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
        labels:
          service: 'frontend'
          component: 'ui'

# Service discovery configuration (for dynamic environments)
# Can be configured for Kubernetes, Consul, etc.
# kubernetes_sd_configs:
#   - role: pod
#     namespaces:
#       names:
#         - default
#         - monitoring