[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
type = "web"
buildCommand = "cd backend && pip install -r requirements.txt"
startCommand = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[[services]]
name = "frontend"
type = "web"
buildCommand = "cd frontend && npm install && npm run build"
startCommand = "cd frontend && npm start"

[env]
PYTHON_VERSION = "3.11"
NODE_VERSION = "18"